language: rust

# sudo: false
# workaround https://github.com/travis-ci/travis-ci/issues/9061
sudo: required

env:
  - RUST_BACKTRACE=1 RUSTFLAGS="-C link-dead-code" # Note that setting the environment variable RUSTFLAGS="-C link-dead-code" during tests build may improve coverage accuracy by preventing dead-code elimination. Do not set this variable when creating release builds since it will increase binary size.

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - rvm install 2.5.1

# for kcov and codecov.io
# addons:
#   apt:
#     packages:
#       - libcurl4-openssl-dev
#       - libelf-dev
#       - libdw-dev
#       - cmake
#       - gcc
#       - binutils-dev
#       - libiberty-dev

# after_success: |
#   wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
#   tar xzf master.tar.gz &&
#   cd kcov-master &&
#   mkdir build &&
#   cd build &&
#   cmake .. &&
#   make &&
#   make install DESTDIR=../../kcov-build &&
#   cd ../.. &&
#   rm -rf kcov-master &&
#   for file in target/debug/ruby_on_rust-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
#   bash <(curl -s https://codecov.io/bash) &&
#   echo "Uploaded code coverage"


after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
