[package]
name = "ruby_on_rust"
version = "0.0.0"
authors = ["Nami.WANG <namiheike@gmail.com>"]

build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.2"
